export const enLocal = {
  translation: {
    active_users:"Active Users",
    all: "All",
    app_analytics:"App Analytics",
    app_analytics_subtitle:"Total x% Conversion Rate",
    conversions:"Conversions",
    dashboard: "Dashboard",
    downloads:"Downloads",
    day: "Day",
    events: "Events",
    insights:"Insights",
    instagram:"Instagram",
    leads:"Leads",
    notification: "Notification",
    offers: "Offers",
    page_views:"Page Views",
    sample:"Sample",
    sessions:"Sessions",
    social_media_analytics:"Social Media Analytics",
    social_media_analytics_subtitle:"Total x% Conversion Rate",
    star:"Star",
    than_last_week:"than last week",
    title: "title",
    tiktok:"Tiktok",
    total_expense:"Total Expense",
    total_incom:"Total Incom",
    traffic:"Traffic",
    twitter:"Twitter",
    website_analytics:"Website Analytics",
    website_analytics_subtitle:"Total x% Conversion Rate",
    week:"Week"
  },
};
