export const faLocal = {
  translation: {
    active_users:"کاربران فعال",
    all: "همه",
    app_analytics:"آمار اپلیکیشن",
    app_analytics_subtitle:"نرخ تبدیل کل x%",
    conversions:"نرخ تبدیل",
    dashboard: "داشبورد",
    downloads:"دانلود",
    day: "روز",
    events: "رویدادها",
    insights:'داده ها',
    instagram:"اینستاگرام",
    leads:"لید",
    notification: "اعلانات",
    offers: "پیشنهادات",
    page_views:"بازدید صفحات",
    rial: "ریال",
    sample: "نمونه",
    sessions:"مراجعات (سشن‌ها)",
    social_media_analytics:"آمار شبکه‌های اجتماعی",
    social_media_analytics_subtitle:"نرخ تبدیل کل x%",
    star:'ستاره',
    than_last_week: "نسبت به هفته گذشته",
    tiktok:"تیک‌تاک",
    title: "عنوان",
    toman: "تومان",
    total_expense: "هزینه کل",
    total_incom: "درآمد کل",
    traffic: "ترافیک",
    twitter:"توئیتر",
    website_analytics: "آمار سایت",
    website_analytics_subtitle: "نرخ تبدیل کل x%",
    week: "هفته",
  },
};
